### ISSUE TITLE
Change to Regex Parameters

### ISSUE THREAD

**Issue by darelf** [lantunes/routd#10]
The following test will pass with version 1.0.5 but will fail with version 1.0.6  The issue seems to be the third route in this test, and the router object will return null.

    public void testRegexRoute() throws Exception {
        Route r1 = new Route("/excavator/imgservlet/:imgid<[0-9]+>");
        Route r2 = new Route("/excavator/imgservlet/:imgid<[0-9]+>/thumbnail");
        Route r3 = new Route("/excavator/imgservlet/blank");
        Router router = new TreeRouter();
        router.add(r1);
        router.add(r2);
        router.add(r3);

        String path = "/excavator/imgservlet/10";
        Route x = router.route(path);
        assertNotNull(x);
        assertEquals(r1, x);
        assertEquals("10", x.getNamedParameter("imgid", path));
    }

**Comment by lantunes** [comment]
This has been fixed in 1.0.7. Please let me know if you see any more problems. Thank you!

**Comment by darelf** [comment]
Thank you! I appreciate the quick response.
